### ISSUE TITLE
Saving file requires additional input

### ISSUE THREAD

**Issue by Matteoverzotti** [TomDeneire/notify-diagnostics.nvim#4]
When saving a file that has an error/warning that is being displayed, it requires another input.

https://github.com/TomDeneire/notify-diagnostics.nvim/assets/58049266/ab68bdfd-3a08-49b4-8bc9-d68258b6c3fc

**Comment by TomDeneire** [comment]
Hi,

thanks for your feedback. I think you may be able to correct this by adding some extra autocommands to the settings:

https://github.com/TomDeneire/notify-diagnostics.nvim?tab=readme-ov-file#default-settings

Perhaps `BufWritePre` will do the trick.

In any case, I'm going to archive this project, because I don't use it myself anymore. It was more of an experiment anyways.

I use https://github.com/RaafatTurki/corn.nvim now, with a very similar effect as my plugin.

All the best,

Tom.
